version: "3.9"
services:
  #Elasticsearch to use as a database for the API
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.1
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512M -Xmx512M
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - qa-network
  #Kibana to visualize the Elaticsearch data
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.5.1
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200    # address of elasticsearch docker container which kibana will connect
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch                                   # kibana will start when elasticsearch has started
    networks:
      - qa-network
networks:
  qa-network:
    external: false
    name: qa-network